### ISSUE TITLE
Request rejected

### ISSUE THREAD

**Issue by boddunarakesh** [Divxeas/Netflix-videos-downloader1#4]
Proxy Status: Off
Getting IP...

--  NF Ripper  --
__________________________

VERSION: 2.0.1.0
__________________________

IP: 117.198.xxx.xxx (IN)
__________________________

Getting Metadata...
Getting High Profile Manifest...
ERROR
{"internalcode":207004,"messageid":815927915860079,"errorcode":1,"errormsg":"Request rejected by key exchange service","timestamp":1641812458}
Traceback (most recent call last):
  File "C:\Users\sccl\Desktop\Netflix-videos-downloader1-main\helpers\Parsers\Netflix\MSLClient.py", line 287, in generate_handshake
    exit(-1)
  File "C:\Users\sccl\AppData\Local\Programs\Python\Python310\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: -1
{"signature":"G1vtG9L1dk15C0pCrE823S4ZcgSckBmijCb42Jiv5RFJJA1kr4imnvKBY2rzd7F/NSic3cNy646eFwTj8Qo/8ah098fwxyVJqlVI0faGWq7ovf638jvF3YgWiodWBZ2quZVKmjgEOPxzQ2IM5kJ9ByHAuQ7Tg0h2Xuv20z77QWtEoF55evD22ysEMyqwEJGsl25b9tJJ4y2D7a19n/uCY0R+wNWFLFnHoyYmlo6qgBBKd3lTISUwo+esF+6YCCl7fwm1VpR4YtwEJd9ZDquVjfGbDnTshltZPTOWIRJdM4k2mpw+1cMzCi0hatnO9y6FGBJOzLd1tL0amLpa1XMEEg==","errordata":"eyJpbnRlcm5hbGNvZGUiOjIwNzAwNCwibWVzc2FnZWlkIjo4MTU5Mjc5MTU4NjAwNzksImVycm9yY29kZSI6MSwiZXJyb3Jtc2ciOiJSZXF1ZXN0IHJlamVjdGVkIGJ5IGtleSBleGNoYW5nZSBzZXJ2aWNlIiwidGltZXN0YW1wIjoxNjQxODEyNDU4fQ==","entityauthdata":{"scheme":"RSA","authdata":{"identity":"Netflix","pubkeyid":"MSL_TRUSTED_NETWORK_SERVER_KEY"}}}

**Comment by anhduca4** [comment]
Same error

**Comment by georgysaumen** [comment]
> Proxy Status: Off Getting IP...
> 
> -- NF Ripper --
> 
> VERSION: 2.0.1.0
> 
> IP: 117.198.xxx.xxx (IN)
> 
> Getting Metadata... Getting High Profile Manifest... ERROR {"internalcode":207004,"messageid":815927915860079,"errorcode":1,"errormsg":"Request rejected by key exchange service","timestamp":1641812458} Traceback (most recent call last): File "C:\Users\sccl\Desktop\Netflix-videos-downloader1-main\helpers\Parsers\Netflix\MSLClient.py", line 287, in generate_handshake exit(-1) File "C:\Users\sccl\AppData\Local\Programs\Python\Python310\lib_sitebuiltins.py", line 26, in **call** raise SystemExit(code) SystemExit: -1 {"signature":"G1vtG9L1dk15C0pCrE823S4ZcgSckBmijCb42Jiv5RFJJA1kr4imnvKBY2rzd7F/NSic3cNy646eFwTj8Qo/8ah098fwxyVJqlVI0faGWq7ovf638jvF3YgWiodWBZ2quZVKmjgEOPxzQ2IM5kJ9ByHAuQ7Tg0h2Xuv20z77QWtEoF55evD22ysEMyqwEJGsl25b9tJJ4y2D7a19n/uCY0R+wNWFLFnHoyYmlo6qgBBKd3lTISUwo+esF+6YCCl7fwm1VpR4YtwEJd9ZDquVjfGbDnTshltZPTOWIRJdM4k2mpw+1cMzCi0hatnO9y6FGBJOzLd1tL0amLpa1XMEEg==","errordata":"eyJpbnRlcm5hbGNvZGUiOjIwNzAwNCwibWVzc2FnZWlkIjo4MTU5Mjc5MTU4NjAwNzksImVycm9yY29kZSI6MSwiZXJyb3Jtc2ciOiJSZXF1ZXN0IHJlamVjdGVkIGJ5IGtleSBleGNoYW5nZSBzZXJ2aWNlIiwidGltZXN0YW1wIjoxNjQxODEyNDU4fQ==","entityauthdata":{"scheme":"RSA","authdata":{"identity":"Netflix","pubkeyid":"MSL_TRUSTED_NETWORK_SERVER_KEY"}}}

CDM is die so u will get that error, u need to dump your personal cdm or wait for leak cdm. U can use this leak cdm for continue using NF Tool

https://drive.google.com/drive/folders/1Nn7VFgqQwq-AHXvYQ6_52cQNbSTY-PMw?usp=sharing

UPDATE (02/03/2022): This CDM is revoked! Sorry!

**Comment by ang3lo-azevedo** [comment]
Same error!

**Comment by georgysaumen** [comment]
> Same error!

The error is depend on CDM, u need to dump ur personal CDM or wait for leak

**Comment by ang3lo-azevedo** [comment]
> > Same error!
> 
> The error is depend on CDM, u need to dump ur personal CDM or wait for leak

And how do I do it on my pc?

**Comment by ang3lo-azevedo** [comment]
> > Same error!
> 
> The error is depend on CDM, u need to dump ur personal CDM or wait for leak

Is there any way to dump the CDM from an android 11 device?

**Comment by georgysaumen** [comment]
You can use this github: https://github.com/wvdumper/dumper for dump your
personal CDM on ur android phone

You need to root and unlock bootloader ur android phone first after run


Vào Th 7, 7 thg 5, 2022 vào lúc 18:15 nos4a2 ***@***.***>
đã viết:

**Comment by ang3lo-azevedo** [comment]
> 

But that method only works on android 10 or older right?

**Comment by georgysaumen** [comment]
No, it doesn't.

Above Android 11

Vào Th 7, 7 thg 5, 2022 vào lúc 18:35 nos4a2 ***@***.***>
đã viết:

**Comment by ang3lo-azevedo** [comment]
I did it!

**Comment by ang3lo-azevedo** [comment]
Does the files have to have the same name as this files?
![image](https://user-images.githubusercontent.com/66081804/167310656-a639e91b-d97d-4e64-ab3f-30fb85059eaf.png)

**Comment by georgysaumen** [comment]
You dont need to change name, copy that 2 files and go to ur NF downloader
folder, locate to \pywidevine\devices\android_general and paste on there
(remember to delete token file on \config\token) before run script

Vào Th 2, 9 thg 5, 2022 vào lúc 01:40 nos4a2 ***@***.***>
đã viết:

**Comment by ang3lo-azevedo** [comment]
It's giving me this error, even though my email and password are right
![image](https://user-images.githubusercontent.com/66081804/167311394-29ddd4fc-fbe4-4d4e-8c1e-667be2064dff.png)

**Comment by ang3lo-azevedo** [comment]
And does it work right with only Widevine L3 and not Widevine L1?

**Comment by ang3lo-azevedo** [comment]
Could you help me @georgesaumen ?

**Comment by CaptainWalkerx** [comment]
@the-nos4a2 if you can solve it can you teach me how to download netflix video please

**Comment by luoei** [comment]
> 

Is there a way now? @the-nos4a2 @georgesaumen @CaptainWalkerx

**Comment by luoei** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key

**Comment by Matka150** [comment]
> https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key

How do I use it in the netflix downloader?

**Comment by luoei** [comment]
> > https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key
> 
> How do I use it in the netflix downloader?

Temporarily put it down, because there are other high-priority tasks, and I hope other people can complete it.

**Comment by georgysaumen** [comment]
This is a new update of NF, u need to change sth on MSLClient.py on
\helpers\Parser\Netflix. Srr I cannot tell you

Vào Th 2, 9 thg 5, 2022 vào lúc 14:14 nos4a2 ***@***.***>
đã viết:

**Comment by georgysaumen** [comment]
Yes, it is. Only High Profile

Vào Th 2, 9 thg 5, 2022 vào lúc 16:20 nos4a2 ***@***.***>
đã viết:
